"""
============================================================
  STOCK UNIVERSE
  Nifty 100 + Midcap 150 symbols for NSE
  All symbols in Yahoo Finance format (.NS suffix)
============================================================
"""

NIFTY100 = [
    # Nifty 50 core
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","SBIN.NS","BAJFINANCE.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "ITC.NS","LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS",
    "TITAN.NS","SUNPHARMA.NS","ULTRACEMCO.NS","WIPRO.NS","NESTLEIND.NS",
    "POWERGRID.NS","NTPC.NS","TMPV.NS","M&M.NS","TECHM.NS",
    "HCLTECH.NS","BAJAJFINSV.NS","ONGC.NS","ADANIENT.NS","COALINDIA.NS",
    "DIVISLAB.NS","DRREDDY.NS","CIPLA.NS","EICHERMOT.NS","HEROMOTOCO.NS",
    "BPCL.NS","TATACONSUM.NS","BRITANNIA.NS","JSWSTEEL.NS","TATASTEEL.NS",
    "INDUSINDBK.NS","GRASIM.NS","HINDALCO.NS","SBILIFE.NS","HDFCLIFE.NS",
    "APOLLOHOSP.NS","BAJAJ-AUTO.NS","ADANIPORTS.NS","UPL.NS","LTM.NS",
    # Nifty Next 50
    "AMBUJACEM.NS","BANKBARODA.NS","BERGEPAINT.NS","BIOCON.NS","BOSCHLTD.NS",
    "CANBK.NS","CHOLAFIN.NS","DABUR.NS","DLF.NS","GODREJCP.NS",
    "HAVELLS.NS","INDHOTEL.NS","IOC.NS","LUPIN.NS","MUTHOOTFIN.NS",
    "NAUKRI.NS","PIDILITIND.NS","PNB.NS","RECLTD.NS","SIEMENS.NS",
    "SRF.NS","TATACOMM.NS","TORNTPHARM.NS","VEDL.NS","VOLTAS.NS",
    "ETERNAL.NS","PAYTM.NS","NYKAA.NS","POLICYBZR.NS","DMART.NS",
]

MIDCAP150 = [
    "ABCAPITAL.NS","APLAPOLLO.NS","ASTRAL.NS","ATUL.NS","AUBANK.NS",
    "AUROPHARMA.NS","BALKRISIND.NS","BANDHANBNK.NS","BEL.NS","BHARATFORG.NS",
    "BHEL.NS","BIKAJI.NS","BLUESTARCO.NS","CAMS.NS","CANFINHOME.NS",
    "CDSL.NS","CESC.NS","CGPOWER.NS","COFORGE.NS","COLPAL.NS",
    "CONCOR.NS","CROMPTON.NS","CUMMINSIND.NS","CYIENT.NS","DALBHARAT.NS",
    "DEEPAKNTR.NS","ELGIEQUIP.NS","EMAMILTD.NS","ENGINERSIN.NS","EXIDEIND.NS",
    "FEDERALBNK.NS","GLENMARK.NS","GMRAIRPORT.NS","GNFC.NS","GODREJPROP.NS",
    "GRANULES.NS","GSPL.NS","HFCL.NS","HONAUT.NS","IDFCFIRSTB.NS",
    "IEX.NS","INDIAMART.NS","INDIANB.NS","INDIGO.NS","JKCEMENT.NS",
    "JSWENERGY.NS","JUBLFOOD.NS","KANSAINER.NS","KARURVYSYA.NS","KEC.NS",
    "KPITTECH.NS","LALPATHLAB.NS","LAURUSLABS.NS","LICHSGFIN.NS","LTTS.NS",
    "MARICO.NS","MAXHEALTH.NS","MCX.NS","METROPOLIS.NS","MFSL.NS",
    "MGL.NS","MOTILALOFS.NS","MPHASIS.NS","MRPL.NS","NAM-INDIA.NS",
    "NATIONALUM.NS","NAVINFLUOR.NS","NBCC.NS","NCC.NS","NMDC.NS",
    "OBEROIRLTY.NS","OFSS.NS","OIL.NS","PAGEIND.NS","PATANJALI.NS",
    "PERSISTENT.NS","PETRONET.NS","PFIZER.NS","PHOENIXLTD.NS","PVRINOX.NS",
    "RADICO.NS","RAILTEL.NS","RAMCOCEM.NS","RITES.NS","SAIL.NS",
    "SCHAEFFLER.NS","SHREECEM.NS","SKFINDIA.NS","SOBHA.NS","SONACOMS.NS",
    "STARHEALTH.NS","SUNTV.NS","SUPREMEIND.NS","SYNGENE.NS","TATACHEM.NS",
    "TATAELXSI.NS","TATAPOWER.NS","TTML.NS","THYROCARE.NS","TIINDIA.NS",
    "TIMKEN.NS","TORNTPOWER.NS","TRENT.NS","TRIDENT.NS","TRITURBINE.NS",
    "TVSHLTD.NS","TVSMOTOR.NS","UBL.NS","UJJIVANSFB.NS","UNIONBANK.NS",
    "UNOMINDA.NS","UCOBANK.NS","VAIBHAVGBL.NS","VBL.NS","VINATIORGA.NS",
    "WELCORP.NS","WHIRLPOOL.NS","YESBANK.NS","ZEEL.NS","ZENSARTECH.NS",
]

# Try to load from nifty500 module if available — else use above lists
try:
    from nifty500 import get_nifty500_symbols
    ALL_STOCKS = get_nifty500_symbols()
except ImportError:
    ALL_STOCKS = list(set(NIFTY100 + MIDCAP150))


def get_all_stocks():
    return ALL_STOCKS


def get_nifty100():
    return NIFTY100


def get_midcap150():
    return MIDCAP150
